services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alamanedocs-app
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - JWT_EXPIRATION=86400000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - alamanedocs-network

networks:
  alamanedocs-network:
    driver: bridge
